# Jekyll
language: en
date_format: ordinal
sass:
  sass_dir: assets/sass
  style: compressed
url: http://www.codebucket.de
baseurl: "/blog"
timezone: Europe/Warsaw
encoding: "utf-8"

# Site settings
title: Codebucket
tagline: "Programmierung seit 2009"
description:
  - "**I am Codebucket**."
  - "17 years old, Java/PHP/JS Developer at Codebucket.de, Owner and Hoster of Razex.de."
author: Codebucket
keywords: "Codebucket, Computer, Java, PHP, JS, Developer, Codebucket.de, Jekyll, Blog, Cracow, Poland, Cloud, Productivity, GitHub, Open Source, Hosting, Razex.de"
copyright: "2013-2017 Codebucket"

# Sitemap settings
collections:
  wiki:
    output: true
    permalink: /wiki/:path/

# Social media
disqus_shortname: codebucketdev
facebook_username: codebucketdev
twitter_username: codebucketdev
linkedin_username:
instagram_username:
pinterest_username:
flickr_username:
github_username: codebucketdev
feed_icon: rss
email:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate_path: "/page/:num/"
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","LICENSE"]

# Gems
gems:
  - jekyll-archives
  - rouge
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
