# Jekyll
language: en
date_format: ordinal
sass:
  sass_dir: assets/sass
  style: compressed
url: https://www.codebucket.de
baseurl: "/blog"
timezone: Europe/Warsaw
encoding: "utf-8"

# Site settings
title: Codebucket
tagline: "Programming since 2013"
description:
  - "**Hey, I'm David Sn**."
  - "18 years old, turns caffeine and pizza into code.  \nAlso previously known as Codebucket."
author: "David Sn"
keywords: "Codebucket, Computer, Java, PHP, JS, Developer, Codebucket.de, Jekyll, Blog, Krakow, Poland, Cloud, Productivity, GitHub, Open Source, Hosting, Razex.de, David Sn, divadsn"
copyright: "2013-2018 David Sn"

# Social media
disqus_shortname: codebucketdev
github_username: divadsn
facebook_username:
twitter_username: divadsn
linkedin_username:
instagram_username: divadsn
pinterest_username:
flickr_username:
feed_icon: rss
email:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate_path: "/page/:num/"
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","LICENSE"]

# Plugins
plugins:
  - rouge
  - jekyll-last-modified-at
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
